#!/usr/bin/env python3
"""Export the completed DeepSeek/Kimi Table 2 comparison."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DEEPSEEK = ROOT / "outputs/main_dynamic_hv_heatmap_20260715/summary.json"
DEFAULT_KIMI = ROOT / "logs/llm_tests/table2_kimi_k3_full_20260717/table2_summary.json"
DEFAULT_DEEPSEEK_AUDIT = (
    ROOT / "logs/llm_tests/table2_deepseek_continuation_20260717/coverage_audit/summary.json"
)
DEFAULT_KIMI_AUDIT = ROOT / "logs/llm_tests/table2_kimi_k3_full_20260717/coverage_audit/summary.json"
DEFAULT_OUT = ROOT / "logs/analysis/table2_model_family_comparison_20260717"
DEFAULT_TEX = ROOT / "release_artifacts/paper_table_exports/table2_model_family_rows.tex"
METHODS = ("LiveOpt", "ReAct+Tools", "OptiMUS", "ORLM", "OptimAI", "OR-Agent")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deepseek-summary", type=Path, default=DEFAULT_DEEPSEEK)
    parser.add_argument("--kimi-summary", type=Path, default=DEFAULT_KIMI)
    parser.add_argument("--deepseek-audit", type=Path, default=DEFAULT_DEEPSEEK_AUDIT)
    parser.add_argument("--kimi-audit", type=Path, default=DEFAULT_KIMI_AUDIT)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--paper-table", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def render_tex(rows: list[dict[str, Any]]) -> str:
    lines = [
        "% Generated by scripts/analysis/export_table2_model_family_comparison.py.",
        r"\newcommand{\TableTwoModelFamilyRows}{%",
    ]
    for row in rows:
        method = r"\method{}" if row["method"] == "LiveOpt" else row["method"]
        backbone = (
            "DeepSeek-V4-Pro (Preview)"
            if row["backbone"] == "DeepSeek-V4-Pro"
            else row["backbone"]
        )
        lines.append(
            f"{method} & {backbone} & "
            f"{100.0 * row['ds_solve_rate']:.1f} & {row['ds_online_quality']:.3f} & "
            f"{100.0 * row['dm_solve_rate']:.1f} & {row['dm_online_quality']:.3f} " + r"\\"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    errors: list[str] = []
    sources = {
        "DeepSeek-V4-Pro": read_json(args.deepseek_summary),
        "Kimi K3 (1M)": read_json(args.kimi_summary),
    }
    for backbone, summary in sources.items():
        if summary.get("stages") != list(range(13)):
            errors.append(f"{backbone}: expected stages t00--t12")
    for label, path in (
        ("DeepSeek-V4-Pro", args.deepseek_audit),
        ("Kimi K3 (1M)", args.kimi_audit),
    ):
        audit = read_json(path)
        if audit.get("status") != "passed":
            errors.append(f"{label}: sequential coverage audit is not passed")

    rows: list[dict[str, Any]] = []
    for backbone, summary in sources.items():
        methods = summary.get("methods") or {}
        for method in METHODS:
            # The new Kimi experiment reruns external methods. LiveOpt's Kimi
            # evidence is the P010 appendix diagnostic, not a full Table 2 row.
            if backbone.startswith("Kimi") and method == "LiveOpt":
                continue
            source = methods.get(method) or {}
            ds = source.get("ds") or {}
            dm = source.get("dm") or {}
            if not ds or not dm:
                errors.append(f"{backbone} {method}: missing DS/DM summary")
                continue
            rows.append(
                {
                    "method": method,
                    "backbone": backbone,
                    "ds_solve_rate": float(ds.get("solved") or 0) / float(ds.get("cells") or 1),
                    "ds_online_quality": float(ds.get("mean_quality") or 0.0),
                    "dm_solve_rate": float(dm.get("solved") or 0) / float(dm.get("cells") or 1),
                    "dm_online_quality": float(dm.get("mean_hv") or 0.0),
                }
            )

    args.out_dir.mkdir(parents=True, exist_ok=True)
    if rows:
        write_csv(args.out_dir / "model_family_rows.csv", rows)
    payload = {
        "status": "passed" if not errors else "incomplete",
        "protocol": "table2_model_family_t00_t12_v1",
        "rows": rows,
        "errors": errors,
    }
    (args.out_dir / "summary.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    if not errors:
        args.paper_table.parent.mkdir(parents=True, exist_ok=True)
        args.paper_table.write_text(render_tex(rows), encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 1 if args.strict and errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
