#!/usr/bin/env python3
"""Summarize saved controller-repeat calls, tokens, and latency without APIs."""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "logs/analysis/liveopt_controller_cost_p010_p015_20260717"
DEFAULT_TEX = ROOT / "release_artifacts/paper_table_exports/liveopt_controller_cost_rows.tex"
RUNS = {
    "LiveOpt": [
        ROOT / f"outputs/liveopt_controller_repeat_p{problem:03d}_liveopt_c{controller}_200x200x3_20260717"
        for problem in (10, 15)
        for controller in (1, 2)
    ],
    "LiveOpt w/o TSS": [
        ROOT / f"outputs/liveopt_controller_repeat_p{problem:03d}_no_tss_c{controller}_200x200x3_20260717"
        for problem in (10, 15)
        for controller in (1, 2)
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--paper-table", type=Path, default=DEFAULT_TEX)
    return parser.parse_args()


def mean(rows: list[dict[str, Any]], key: str) -> float:
    return statistics.mean(float(row[key]) for row in rows)


def inspect_run(path: Path) -> dict[str, Any]:
    trace_path = path / "trace/deepseek_calls.jsonl"
    summary_path = path / "summary.json"
    trace = [json.loads(line) for line in trace_path.open(encoding="utf-8")]
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if any(row.get("error") for row in trace):
        raise ValueError(f"provider error recorded in {trace_path}")
    usage = [row.get("usage") or {} for row in trace]
    return {
        "run_dir": str(path.relative_to(ROOT)),
        "calls": len(trace),
        "prompt_tokens": sum(int(item.get("prompt_tokens") or 0) for item in usage),
        "completion_tokens": sum(int(item.get("completion_tokens") or 0) for item in usage),
        "total_tokens": sum(int(item.get("total_tokens") or 0) for item in usage),
        "prompt_cache_hit_tokens": sum(int(item.get("prompt_cache_hit_tokens") or 0) for item in usage),
        "provider_latency_seconds": sum(float(row.get("latency_seconds") or 0.0) for row in trace),
        "wall_seconds": float(summary.get("latency_seconds") or 0.0),
    }


def main() -> None:
    args = parse_args()
    methods: list[dict[str, Any]] = []
    for method, paths in RUNS.items():
        runs = [inspect_run(path) for path in paths]
        methods.append(
            {
                "method": method,
                "trajectory_count": len(runs),
                "mean_calls": mean(runs, "calls"),
                "mean_prompt_tokens": mean(runs, "prompt_tokens"),
                "mean_completion_tokens": mean(runs, "completion_tokens"),
                "mean_total_tokens": mean(runs, "total_tokens"),
                "mean_prompt_cache_hit_tokens": mean(runs, "prompt_cache_hit_tokens"),
                "mean_provider_latency_seconds": mean(runs, "provider_latency_seconds"),
                "mean_wall_seconds": mean(runs, "wall_seconds"),
                "runs": runs,
            }
        )

    payload = {
        "protocol": "saved_p010_p015_controller_repeat_cost_v1",
        "provider_or_api_calls": False,
        "scope": "two new controller trajectories on each of P010 and P015; three numerical seeds per trajectory",
        "pricing": "not inferred; provider-reported token and latency records only",
        "methods": methods,
    }
    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "summary.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    labels = {"LiveOpt": r"\method{}", "LiveOpt w/o TSS": r"\method{} w/o TSS"}
    lines = [
        "% Generated by scripts/analysis/export_liveopt_controller_cost_summary.py.",
        r"\newcommand{\LiveOptControllerCostRows}{%",
    ]
    for row in methods:
        lines.append(
            f"{labels[row['method']]} & {row['trajectory_count']} & {row['mean_calls']:.1f} & "
            f"{row['mean_total_tokens'] / 1000.0:.1f}k & "
            f"{row['mean_provider_latency_seconds'] / 60.0:.1f} & "
            f"{row['mean_wall_seconds'] / 60.0:.1f} " + r"\\"
        )
    lines.append("}")
    args.paper_table.parent.mkdir(parents=True, exist_ok=True)
    args.paper_table.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
