#!/usr/bin/env python3
"""Export one real data patch and one real slot-patch diff for the appendix."""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from evo2.agents.liveopt_dynamic_impl import apply_public_context_patch
from scripts.llm_tests.run_liveopt_dynamic_nldo_benchmark_full import public_context_with_loaded_tables


BENCHMARK = ROOT / "data/evo2_dynoptbench/public_csv/nldo_15episodes_12updates_csv.jsonl"
DM_SOURCE = ROOT / "outputs/liveopt_matched_full_p010_p015_200x200x10_20260714/NLDO/evo2_limit0.jsonl"
DEFAULT_OUT = ROOT / "logs/analysis/liveopt_real_patch_diff_20260717"
DEFAULT_TEX = ROOT / "release_artifacts/paper_table_exports/liveopt_real_patch_diff.tex"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--paper-tex", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def repo_path(path: Path) -> str:
    resolved = path.resolve()
    try:
        return str(resolved.relative_to(ROOT))
    except ValueError:
        return str(resolved)


def load_episode(episode_id: str) -> dict[str, Any]:
    with BENCHMARK.open(encoding="utf-8") as handle:
        for line in handle:
            episode = json.loads(line)
            if episode.get("episode_id") == episode_id:
                return episode
    raise ValueError(f"episode not found: {episode_id}")


def load_run(path: Path, episode_id: str, run_seed: int = 0) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            if row.get("episode_id") == episode_id and int(row.get("run_seed", -1)) == run_seed:
                return row
    raise ValueError(f"run not found: {episode_id} seed {run_seed}")


def render_tex(data_before: float, data_after: float, slot_lines: list[str]) -> str:
    slot_text = "\n".join(slot_lines)
    return rf"""% Generated by scripts/analysis/export_liveopt_real_patch_diff.py.
\begin{{figure}}[!htbp]
\centering
\begin{{minipage}}[t]{{0.31\linewidth}}
\textbf{{Public-data change: P015-t02}}\\[-2pt]
\begin{{Verbatim}}[fontsize=\scriptsize]
tables/machines[id=M04]
- energy_per_cpu: {data_before:g}
+ energy_per_cpu: {data_after:g}
\end{{Verbatim}}
\vspace{{-4pt}}
The remaining public fields and both editable functions are unchanged.
\end{{minipage}}\hfill
\begin{{minipage}}[t]{{0.66\linewidth}}
\textbf{{Evaluation-function change: P010-t02}}\\[-2pt]
\begin{{Verbatim}}[fontsize=\scriptsize]
{slot_text}
\end{{Verbatim}}
\vspace{{-4pt}}
The shown lines are copied from the saved code change. Comments and unchanged lines are omitted.
\end{{minipage}}
\caption{{\textbf{{Two real localized updates.}} P015-t02 changes one machine's energy coefficient in the public table, so the Workbench does not change. P010-t02 introduces a congestion rule, so the language model changes only the evaluation function. The decision-definition function remains unchanged. Both updates must evaluate a small public example before search.}}
\label{{fig:appendix-real-patch-diff}}
\end{{figure}}
"""


def main() -> int:
    args = parse_args()
    errors: list[str] = []

    data_episode = load_episode("NLDO-P015")
    data_run = load_run(DM_SOURCE, "NLDO-P015")
    data_updates = list(data_run.get("update_results") or [])
    context = public_context_with_loaded_tables(data_episode)
    for update in data_updates[:1]:
        context = apply_public_context_patch(context, (update.get("restart") or {}).get("data_patch") or {})
    machine_before = next(row for row in (context.get("tables") or {}).get("machines", []) if row.get("id") == "M04")
    data_before = float(machine_before["energy_per_cpu"])
    data_update = data_updates[1]
    data_patch = (data_update.get("restart") or {}).get("data_patch") or {}
    updated_context = apply_public_context_patch(context, data_patch)
    machine_after = next(
        row for row in (updated_context.get("tables") or {}).get("machines", []) if row.get("id") == "M04"
    )
    data_after = float(machine_after["energy_per_cpu"])
    if abs(data_before - 0.23) > 1e-12 or abs(data_after - 0.285) > 1e-12:
        errors.append(f"unexpected P015-t02 data transition: {data_before}->{data_after}")
    if data_update.get("setup_code") != data_updates[0].get("setup_code") or data_update.get("fitness_code") != data_updates[0].get("fitness_code"):
        errors.append("P015-t02 is not a byte-identical data-only slot transition")

    dm_run = load_run(DM_SOURCE, "NLDO-P010")
    dm_updates = list(dm_run.get("update_results") or [])
    before_slot = str(dm_updates[0].get("fitness_code") or "")
    after_slot = str(dm_updates[1].get("fitness_code") or "")
    full_slot_diff = list(
        difflib.unified_diff(
            before_slot.splitlines(),
            after_slot.splitlines(),
            fromfile="P010-t01/fitness.py",
            tofile="P010-t02/fitness.py",
            lineterm="",
        )
    )
    if dm_updates[0].get("setup_code") != dm_updates[1].get("setup_code"):
        errors.append("P010-t02 unexpectedly changes setup.py")
    expected_added_lines = [
        '+    congestion_anchor_set = set()',
        '+    for oid, o in data["order_by_id"].items():',
        '+        if abs(o["x"] - 48) < 1e-9 and abs(o["y"] - 11) < 1e-9:',
        '+            congestion_anchor_set.add(oid)',
        '+            break   # at most one anchor',
        '+        prev_oid = None   # no order before first stop',
        '+            if prev_oid in congestion_anchor_set or oid in congestion_anchor_set:',
        '+                leg_dist *= 1.25',
        '+            prev_oid = oid',
        '+        if prev_oid in congestion_anchor_set:',
        '+            leg_dist *= 1.25',
    ]
    missing_lines = [line for line in expected_added_lines if line not in full_slot_diff]
    if missing_lines:
        errors.append("saved P010-t02 slot diff no longer contains the appendix excerpt")
    slot_excerpt = [
        "--- P010-t01/fitness.py",
        "+++ P010-t02/fitness.py",
        "@@ congestion anchor @@",
        *expected_added_lines[:5],
        "@@ route traversal @@",
        *expected_added_lines[5:9],
        "@@ return-to-depot leg @@",
        *expected_added_lines[9:],
    ]

    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.paper_tex.parent.mkdir(parents=True, exist_ok=True)
    args.paper_tex.write_text(render_tex(data_before, data_after, slot_excerpt), encoding="utf-8")
    evidence = {
        "status": "passed" if not errors else "failed",
        "protocol": "real_data_and_slot_patch_diff_v1",
        "benchmark": repo_path(BENCHMARK),
        "benchmark_sha256": sha256_file(BENCHMARK),
        "data_patch": {
            "episode_id": "NLDO-P015",
            "stage": 2,
            "run_seed": 0,
            "source": repo_path(DM_SOURCE),
            "source_sha256": sha256_file(DM_SOURCE),
            "natural_language_update": data_update.get("natural_language_update"),
            "patch": data_patch,
            "before": data_before,
            "after": data_after,
            "setup_byte_identical": data_update.get("setup_code") == data_updates[0].get("setup_code"),
            "fitness_byte_identical": data_update.get("fitness_code") == data_updates[0].get("fitness_code"),
        },
        "slot_patch": {
            "episode_id": "NLDO-P010",
            "stage": 2,
            "run_seed": 0,
            "source": repo_path(DM_SOURCE),
            "source_sha256": sha256_file(DM_SOURCE),
            "natural_language_update": dm_updates[1].get("natural_language_update"),
            "data_patch": (dm_updates[1].get("restart") or {}).get("data_patch") or {},
            "setup_byte_identical": dm_updates[0].get("setup_code") == dm_updates[1].get("setup_code"),
            "full_unified_diff": full_slot_diff,
            "paper_excerpt": slot_excerpt,
        },
        "paper_tex": repo_path(args.paper_tex),
        "errors": errors,
    }
    (args.out_dir / "evidence.json").write_text(
        json.dumps(evidence, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(json.dumps(evidence, ensure_ascii=False, indent=2, sort_keys=True))
    return 1 if args.strict and errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
