#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import fmean
from typing import Any


METHODS = (
    ("LiveOpt", "liveopt"),
    ("LiveOpt w/o TSS", "no_tss"),
    ("Fixed Warm", "fixed_warm"),
    ("Fixed Full", "fixed_full"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit and export the four-method matched LiveOpt ablation.")
    for _, key in METHODS:
        parser.add_argument(f"--{key.replace('_', '-')}-run-dir", type=Path, required=True)
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-tex", type=Path, required=True)
    parser.add_argument(
        "--output-stage-tex",
        type=Path,
        help="Optional compact P010--P015 by t01--t12 four-method HV table.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    summaries: list[dict[str, Any]] = []
    rows_by_key: dict[str, list[dict[str, str]]] = {}
    for label, key in METHODS:
        run_dir = getattr(args, f"{key}_run_dir")
        rows = load_metric_rows(run_dir)
        rows_by_key[key] = rows
        summary = summarize_method(label, key, run_dir, rows)
        summaries.append(summary)
    liveopt_hv = float(summaries[0]["all_hv"])
    for summary in summaries:
        summary["delta_hv"] = float(summary["all_hv"]) - liveopt_hv
    payload = {
        "protocol": "liveopt_no_tss_and_restart_ablation_p010_p015_200x200x10_v2",
        "methods": summaries,
        "expected_cells_per_method": 720,
        "views": {"routing": ["NLDO-P010", "NLDO-P011", "NLDO-P012"], "cloud": ["NLDO-P013", "NLDO-P014", "NLDO-P015"]},
    }
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_tex.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    args.output_tex.write_text(render_tex(summaries), encoding="utf-8")
    if args.output_stage_tex is not None:
        args.output_stage_tex.parent.mkdir(parents=True, exist_ok=True)
        args.output_stage_tex.write_text(render_stage_tex(rows_by_key), encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


def load_metric_rows(run_dir: Path) -> list[dict[str, str]]:
    candidates = [
        run_dir / "reference_metrics" / "reference_stage_metrics.csv",
        run_dir / "liveopt" / "reference_metrics" / "reference_stage_metrics.csv",
    ]
    path = next((item for item in candidates if item.exists()), None)
    if path is None:
        raise FileNotFoundError(f"reference-stage metrics not found under {run_dir}")
    with path.open(encoding="utf-8", newline="") as handle:
        rows = [dict(row) for row in csv.DictReader(handle)]
    return [
        row
        for row in rows
        if 10 <= int(str(row.get("episode_id", "NLDO-P000")).split("P")[-1]) <= 15
        and int(row.get("stage_index") or 0) in range(1, 13)
    ]


def summarize_method(label: str, key: str, run_dir: Path, rows: list[dict[str, str]]) -> dict[str, Any]:
    cells = {(row["episode_id"], int(row["stage_index"]), int(row["run_seed"])) for row in rows}
    if len(rows) != 720 or len(cells) != 720:
        raise ValueError(f"{label}: expected 720 unique update cells, got {len(rows)} rows/{len(cells)} cells")
    solve = sum(parse_bool(row.get("true_pass")) and parse_bool(row.get("feasible")) for row in rows)
    by_family: dict[str, list[float]] = defaultdict(list)
    all_hv: list[float] = []
    all_igd: list[float] = []
    for row in rows:
        episode_number = int(row["episode_id"].split("P")[-1])
        family = "routing" if episode_number <= 12 else "cloud"
        hv = float(row.get("normalized_hv") or 0.0) if parse_bool(row.get("true_pass")) else 0.0
        by_family[family].append(hv)
        all_hv.append(hv)
        if row.get("igd") not in {None, ""}:
            all_igd.append(float(row["igd"]))
    return {
        "method": label,
        "key": key,
        "run_dir": str(run_dir),
        "solve_count": solve,
        "solve_total": len(rows),
        "above_reference_cells": sum(float(row.get("normalized_hv") or 0.0) > 1.0 + 1e-9 for row in rows),
        "max_hv_ratio": max(float(row.get("normalized_hv") or 0.0) for row in rows),
        "routing_hv": fmean(by_family["routing"]),
        "cloud_hv": fmean(by_family["cloud"]),
        "all_hv": fmean(all_hv),
        "all_igd": fmean(all_igd) if all_igd else None,
    }


def parse_bool(value: Any) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes"}


def render_tex(summaries: list[dict[str, Any]]) -> str:
    lines = [
        "% Generated by scripts/analysis/export_liveopt_matched_ablation_paper.py.",
        r"\newcommand{\LiveOptMatchedAblationRows}{%",
    ]
    colors = ["LiveOptPale", "LiveOptBaselineRowA", "LiveOptBaselineRowB", "LiveOptBaselineRowA"]
    for index, summary in enumerate(summaries):
        solve = rf"\RateFrac{{{summary['solve_count']}}}{{{summary['solve_total']}}}"
        delta = r"\textemdash{}" if index == 0 else f"${summary['delta_hv']:+.3f}$"
        label = str(summary["method"])
        if index == 0:
            label = r"\methodours"
        lines.extend(
            [
                rf"\rowcolor{{{colors[index]}}}",
                f"{label} & {solve} & {summary['routing_hv']:.3f} & {summary['cloud_hv']:.3f} & {summary['all_hv']:.3f} & {delta} " + r"\\",
            ]
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_stage_tex(rows_by_key: dict[str, list[dict[str, str]]]) -> str:
    """Render seed-mean formal HV for four methods in each problem--stage cell."""

    episodes = [f"NLDO-P{number:03d}" for number in range(10, 16)]
    means: dict[tuple[str, str, int], float] = {}
    for _, key in METHODS:
        grouped: dict[tuple[str, int], list[float]] = defaultdict(list)
        for row in rows_by_key[key]:
            episode_id = str(row["episode_id"])
            stage = int(row["stage_index"])
            hv = float(row.get("normalized_hv") or 0.0) if parse_bool(row.get("true_pass")) else 0.0
            grouped[(episode_id, stage)].append(hv)
        for episode_id in episodes:
            for stage in range(1, 13):
                values = grouped[(episode_id, stage)]
                if len(values) != 10:
                    raise ValueError(
                        f"{key} {episode_id} t{stage:02d}: expected 10 formal HV values, got {len(values)}"
                    )
                means[(key, episode_id, stage)] = fmean(values)

    keys = [key for _, key in METHODS]

    def render_values(values: list[float]) -> str:
        best = max(values)
        rendered = [
            rf"\textbf{{{value:.3f}}}" if abs(value - best) <= 5e-7 else f"{value:.3f}"
            for value in values
        ]
        return r"\AblationHVCell{" + "}{".join(rendered) + "}"

    problem_summaries: list[str] = []
    for episode_id in episodes:
        values = [fmean(means[(key, episode_id, stage)] for stage in range(1, 13)) for key in keys]
        problem_summaries.append(render_values(values))

    family_summaries: dict[str, str] = {}
    for family, family_episodes in {
        "Routing": episodes[:3],
        "Cloud": episodes[3:],
    }.items():
        values = [
            fmean(means[(key, episode_id, stage)] for episode_id in family_episodes for stage in range(1, 13))
            for key in keys
        ]
        family_summaries[family] = render_values(values)

    lines = [
        "% Generated by scripts/analysis/export_liveopt_matched_ablation_paper.py.",
        r"\newcommand{\LiveOptMatchedStageHVPHeader}{%",
        " & " + " & ".join(rf"\textbf{{{episode_id.replace('NLDO-', '')}}}" for episode_id in episodes) + r" \\",
        r"\rowcolor{LiveOptTableHeader}",
        r"\scriptsize\textbf{Order} & " + " & ".join(r"\AblationHVOrder" for _ in episodes) + r" \\",
        "}",
        r"\newcommand{\LiveOptMatchedStageHVSummaryRows}{%",
        r"\rowcolor{LiveOptTypeSummary}",
        r"\textbf{Type} & \multicolumn{3}{c}{\textbf{Routing}\quad "
        + family_summaries["Routing"]
        + r"} & \multicolumn{3}{c}{\textbf{Cloud}\quad "
        + family_summaries["Cloud"]
        + r"} \\",
        "}",
        r"\newcommand{\LiveOptMatchedStageHVRows}{%",
        r"\textbf{All-t} & " + " & ".join(problem_summaries) + r" \\",
    ]
    for stage in range(1, 13):
        cells: list[str] = []
        for episode_id in episodes:
            values = [means[(key, episode_id, stage)] for key in keys]
            cells.append(render_values(values))
        if stage % 2 == 0:
            lines.append(r"\rowcolor{LiveOptBaselineRowB}")
        lines.append(f"t{stage:02d} & " + " & ".join(cells) + r" \\")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
