#!/usr/bin/env python3
"""Export compact LaTeX tables from the audited restart-shadow assembly."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from statistics import mean
from typing import Any


METHODS = ("LiveOpt", "Fixed Warm", "Fixed Full")


def main() -> int:
    args = parse_args()
    metrics = {method: load_rows(args.assembly_dir, method, "reference_stage_metrics.csv") for method in METHODS}
    runtime = {method: load_rows(args.assembly_dir, method, "runtime_stage_metrics.csv") for method in METHODS}
    args.aggregate_out.parent.mkdir(parents=True, exist_ok=True)
    args.problem_out.parent.mkdir(parents=True, exist_ok=True)
    args.aggregate_out.write_text(render_aggregate(metrics, runtime), encoding="utf-8")
    args.problem_out.write_text(render_problem_table(metrics), encoding="utf-8")
    print(args.aggregate_out)
    print(args.problem_out)
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assembly-dir", type=Path, required=True)
    parser.add_argument("--aggregate-out", type=Path, required=True)
    parser.add_argument("--problem-out", type=Path, required=True)
    return parser.parse_args()


def load_rows(assembly_dir: Path, method: str, name: str) -> list[dict[str, str]]:
    method_dir = method.lower().replace(" ", "_")
    path = assembly_dir / method_dir / "reference_metrics" / name
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def render_aggregate(
    metrics: dict[str, list[dict[str, str]]], runtime: dict[str, list[dict[str, str]]]
) -> str:
    body = []
    for method in METHODS:
        cells = {}
        for view in ("DS", "DM"):
            selected_metrics = [row for row in metrics[method] if profile(row["episode_id"]) == view]
            selected_runtime = [row for row in runtime[method] if profile(row["episode_id"]) == view]
            metric = "normalized_score" if view == "DS" else "normalized_hv"
            feasible = sum(truthy(row.get("feasible")) for row in selected_metrics)
            total = len(selected_metrics)
            cells[view] = {
                "solve": f"\\RateFrac{{{feasible}}}{{{total}}}",
                "quality": mean(as_float(row.get(metric)) for row in selected_metrics),
                "generations": mean(as_float(row.get("executed_generations")) for row in selected_runtime),
            }
            if view == "DM":
                cells[view]["t11"] = mean(
                    as_float(row.get(metric))
                    for row in selected_metrics
                    if int(row.get("stage_index") or 0) == 11
                )
                cells[view]["t12"] = mean(
                    as_float(row.get(metric))
                    for row in selected_metrics
                    if int(row.get("stage_index") or 0) == 12
                )
        body.append(
            f"{method} & {cells['DS']['quality']:.3f} & {cells['DS']['generations']:.1f} & "
            f"{cells['DM']['quality']:.3f} & {cells['DM']['t11']:.3f} & "
            f"{cells['DM']['t12']:.3f} & {cells['DM']['generations']:.1f} \\\\"
        )
    return "\n".join(
        [
            "% Auto-generated by scripts/analysis/export_liveopt_restart_shadow_paper_tables.py",
            "\\begin{table}[!htbp]",
            "\\centering",
            "\\DenseResultTableSetup",
            "\\begin{tabular*}{0.98\\linewidth}{@{\\extracolsep{\\fill}}lcccccc@{}}",
            "\\toprule",
            "\\TableHead",
            "Variant & DS Quality & DS Gen. & DM HV & t11 HV & t12 HV & DM Gen. \\\\",
            "\\midrule",
            *body,
            "\\bottomrule",
            "\\end{tabular*}",
            "\\caption{\\textbf{Restart actions from the same incoming population.} All methods solve all 360 DS and 720 DM time-step--seed results. Only LiveOpt supplies the state for the next update. Fixed Warm and Fixed Full change the current restart action only. All rows use population 200, a 200-generation limit, 10 seeds, and the same stopping rule, which does not use the held-out reference. Quality is normalized scalar score for DS and held-out-reference HV ratio for DM. Gen. is the mean generation count. The t11/t12 columns show LiveOpt's 0.053/0.099 gains over Fixed Warm.}",
            "\\label{tab:main-restart-ablation}",
            "\\end{table}",
            "",
        ]
    )


def render_problem_table(metrics: dict[str, list[dict[str, str]]]) -> str:
    indexed = {
        method: group_quality(rows)
        for method, rows in metrics.items()
    }
    body = []
    for number in range(10, 16):
        episode = f"NLDO-P{number:03d}"
        all_values = [mean(indexed[method][episode][stage] for stage in range(1, 13)) for method in METHODS]
        late_values = [mean(indexed[method][episode][stage] for stage in (11, 12)) for method in METHODS]
        body.append(
            f"P{number:03d} & "
            + " & ".join(f"{value:.3f}" for value in all_values + late_values)
            + " \\\\"
        )
    return "\n".join(
        [
            "% Auto-generated by scripts/analysis/export_liveopt_restart_shadow_paper_tables.py",
            "\\begin{table}[!htbp]",
            "\\centering",
            "\\DenseResultTableSetup",
            "\\begin{tabular*}{0.94\\linewidth}{@{\\extracolsep{\\fill}}lcccccc@{}}",
            "\\toprule",
            "\\TableHead",
            "& \\multicolumn{3}{c}{All t01--t12} & \\multicolumn{3}{c}{Disruptive updates t11--t12} \\\\",
            "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
            "Episode & LiveOpt & Warm & Full & LiveOpt & Warm & Full \\\\",
            "\\midrule",
            *body,
            "\\bottomrule",
            "\\end{tabular*}",
            "\\caption{\\textbf{Online quality for the six Pareto episodes.} All three policies have 100\\% solve rate. Each value is the normalized-HV mean over 10 seeds after infeasible results are set to zero. Every restart choice begins with the same incoming population. The right block isolates the disruptive t11--t12 updates. Every time step uses a held-out 500$\\times$500$\\times$10 reference.}",
            "\\label{tab:restart-p010-p015-problems}",
            "\\end{table}",
            "",
        ]
    )


def group_quality(rows: list[dict[str, str]]) -> dict[str, dict[int, float]]:
    grouped: dict[str, dict[int, list[float]]] = {}
    for row in rows:
        episode = str(row["episode_id"])
        if profile(episode) != "DM":
            continue
        stage = int(row["stage_index"])
        grouped.setdefault(episode, {}).setdefault(stage, []).append(as_float(row.get("normalized_hv")))
    return {
        episode: {stage: mean(values) for stage, values in stages.items()}
        for episode, stages in grouped.items()
    }


def profile(episode_id: str) -> str:
    return "DS" if int(episode_id.rsplit("P", 1)[1]) <= 9 else "DM"


def as_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def truthy(value: Any) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes"}


if __name__ == "__main__":
    raise SystemExit(main())
