#!/usr/bin/env python3
"""Export the completed P010 three-controller cross-model stability check."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from statistics import mean, stdev
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.analysis.export_kimi_model_family_q2 import (  # noqa: E402
    DEFAULT_KIMI_ROOT,
    deepseek_run,
    kimi_run,
    load_controller,
    write_csv,
)


DEFAULT_OUT = ROOT / "logs/analysis/liveopt_p010_model_family_stability_20260717"
DEFAULT_TEX = ROOT / "release_artifacts/paper_table_exports/liveopt_p010_model_family_rows.tex"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kimi-root", type=Path, default=DEFAULT_KIMI_ROOT)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--paper-table", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def render_tex(summary: list[dict[str, Any]]) -> str:
    lines = [
        "% Generated by scripts/analysis/export_p010_model_family_stability.py.",
        r"\newcommand{\LiveOptPZeroTenModelFamilyRows}{%",
    ]
    for row in summary:
        display_family = (
            "DeepSeek-V4-Pro (Preview)"
            if row["model_family"] == "DeepSeek-V4-Pro"
            else row["model_family"]
        )
        lines.append(
            f"{display_family} & {row['valid_controllers']}/3 & "
            f"{100.0 * row['solve_rate']:.1f} & "
            f"${row['online_quality_mean']:.3f} \\pm {row['online_quality_sd']:.3f}$ & "
            f"{row['online_quality_min']:.3f}--{row['online_quality_max']:.3f} " + r"\\"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    errors: list[str] = []
    controllers: list[dict[str, Any]] = []
    for family in ("DeepSeek-V4-Pro", "Kimi K3 (1M)"):
        for controller in range(3):
            run_dir = (
                deepseek_run("NLDO-P010", controller)
                if family == "DeepSeek-V4-Pro"
                else kimi_run(args.kimi_root, "NLDO-P010", controller)
            )
            record, _ = load_controller(
                family,
                "NLDO-P010",
                controller,
                run_dir,
                errors,
            )
            controllers.append(record)

    summary: list[dict[str, Any]] = []
    for family in ("DeepSeek-V4-Pro", "Kimi K3 (1M)"):
        rows = [row for row in controllers if row["model_family"] == family]
        qualities = [float(row["online_quality"]) for row in rows]
        summary.append(
            {
                "model_family": family,
                "controllers": len(rows),
                "valid_controllers": sum(float(row["solve_rate"]) == 1.0 for row in rows),
                "solve_rate": mean(float(row["solve_rate"]) for row in rows),
                "online_quality_mean": mean(qualities),
                "online_quality_sd": stdev(qualities),
                "online_quality_min": min(qualities),
                "online_quality_max": max(qualities),
            }
        )

    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_csv(args.out_dir / "controller_summary.csv", controllers)
    write_csv(args.out_dir / "model_family_summary.csv", summary)
    payload = {
        "status": "passed" if not errors else "incomplete",
        "protocol": "liveopt_p010_model_family_stability_3controller_v1",
        "scope": "appendix stability diagnostic; not the main Q2 baseline comparison",
        "fixed": {
            "episode": "NLDO-P010",
            "controller_trajectories": 3,
            "numerical_seeds": [0, 1, 2],
            "reported_states": list(range(1, 13)),
            "population_size": 200,
            "generation_cap": 200,
            "archive_limit": 500,
            "restart_choices": "frozen verified Warm/Full choices",
        },
        "controllers": controllers,
        "summary": summary,
        "errors": errors,
    }
    (args.out_dir / "summary.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    if not errors:
        args.paper_table.parent.mkdir(parents=True, exist_ok=True)
        args.paper_table.write_text(render_tex(summary), encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 1 if args.strict and errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
