#!/usr/bin/env python3
"""Freeze the latest reference-robustness evidence into a paper table.

The inputs are offline audit products: deterministic reference thinning,
HV-box recomputation, and archive-cap diagnostics.  No optimization or model
provider is invoked.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_THINNING = ROOT / "logs/analysis/liveopt_reference_thinning_latest_20260715/sensitivity.json"
DEFAULT_ROBUSTNESS = ROOT / "logs/analysis/liveopt_reference_robustness_latest_20260715/reference_robustness_audit.json"
DEFAULT_ARCHIVE = ROOT / "logs/analysis/liveopt_archive_diagnostics_latest_20260715/archive.json"
DEFAULT_OUT = ROOT / "logs/analysis/liveopt_reference_evidence_20260715/summary.json"
DEFAULT_TEX = ROOT / "release_artifacts/paper_table_exports/liveopt_reference_sensitivity_rows.tex"
EXPECTED_REFERENCE_SHA256 = "50126c25eb837bdbf2dbc2e7710226472027a1a880305d331dc006438a02c5e5"
METHODS = (
    ("LiveOpt", r"\method{}"),
    ("Sequential Warm", "Sequential Warm"),
    ("Sequential Full", "Sequential Full"),
    ("LiveOpt w/o TSS", r"\method{} w/o TSS"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--thinning", type=Path, default=DEFAULT_THINNING)
    parser.add_argument("--robustness", type=Path, default=DEFAULT_ROBUSTNESS)
    parser.add_argument("--archive", type=Path, default=DEFAULT_ARCHIVE)
    parser.add_argument("--out-json", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--paper-table", type=Path, default=DEFAULT_TEX)
    parser.add_argument("--strict", action="store_true")
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_tex(rows: list[dict[str, Any]]) -> str:
    lines = [
        "% Generated by scripts/analysis/export_liveopt_reference_robustness_table.py.",
        r"\newcommand{\LiveOptReferenceSensitivityRows}{%",
    ]
    for row in rows:
        lines.append(
            f"{row['tex_label']} & {row['thin_75']:+.3f} & {row['thin_50']:+.3f} & "
            f"{row['thin_25']:+.3f} & {row['box_100']:.3f} & {row['box_110']:.3f} & "
            f"{row['box_125']:.3f} " + r"\\"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    thinning = json.loads(args.thinning.read_text(encoding="utf-8"))
    robustness = json.loads(args.robustness.read_text(encoding="utf-8"))
    archive = json.loads(args.archive.read_text(encoding="utf-8"))

    thin = {
        (str(row["method"]), float(row["reference_fraction"])): row
        for row in thinning.get("rows") or []
    }
    boxes = {
        (str(row["method"]), float(row["box_scale"])): row
        for row in robustness.get("sensitivity") or []
    }
    errors: list[str] = []
    if robustness.get("reference_sha256") != EXPECTED_REFERENCE_SHA256:
        errors.append("unexpected held-out reference checksum")
    if robustness.get("mapping_errors"):
        errors.append(f"{len(robustness['mapping_errors'])} stage-mapping errors")
    if robustness.get("metric_errors"):
        errors.append(f"{len(robustness['metric_errors'])} metric-recomputation errors")
    if int(robustness.get("reference_stage_count") or 0) != 72:
        errors.append("reference audit does not cover 72 P010--P015 update stages")

    rows: list[dict[str, Any]] = []
    for method, tex_label in METHODS:
        try:
            row = {
                "method": method,
                "tex_label": tex_label,
                "thin_75": float(thin[(method, 0.75)]["delta_from_full"]),
                "thin_50": float(thin[(method, 0.5)]["delta_from_full"]),
                "thin_25": float(thin[(method, 0.25)]["delta_from_full"]),
                "box_100": float(boxes[(method, 1.0)]["mean_hv_ratio"]),
                "box_110": float(boxes[(method, 1.1)]["mean_hv_ratio"]),
                "box_125": float(boxes[(method, 1.25)]["mean_hv_ratio"]),
                "above_100": int(boxes[(method, 1.0)]["above_reference_cells"]),
                "above_110": int(boxes[(method, 1.1)]["above_reference_cells"]),
                "above_125": int(boxes[(method, 1.25)]["above_reference_cells"]),
            }
        except KeyError as exc:
            errors.append(f"missing sensitivity cell for {method}: {exc}")
            continue
        for fraction in (0.25, 0.5, 0.75, 1.0):
            cell = thin.get((method, fraction))
            if cell is None or int(cell.get("stage_seed_observations") or 0) != 720:
                errors.append(f"{method}: thinning fraction {fraction} is not a 720-cell result")
        for scale in (1.0, 1.1, 1.25):
            cell = boxes.get((method, scale))
            if cell is None or int(cell.get("stage_seed_cells") or 0) != 720:
                errors.append(f"{method}: box scale {scale} is not a 720-cell result")
        rows.append(row)

    archive_rows = archive.get("rows") or []
    if {row.get("episode_id") for row in archive_rows} != {
        f"NLDO-P{number:03d}" for number in range(10, 16)
    }:
        errors.append("archive diagnostics do not cover P010--P015")
    cap_active_cells = sum(
        round(float(row.get("cap_active_rate") or 0.0) * int(row.get("stage_seed_observations") or 0))
        for row in archive_rows
    )
    if int(archive.get("archive_cap") or 0) != 500:
        errors.append("archive diagnostics do not use cap 500")
    if cap_active_cells:
        errors.append(f"archive cap was active in {cap_active_cells} cells")

    above = robustness.get("above_reference_cells") or []
    no_tss_above = [row for row in above if row.get("method") == "LiveOpt w/o TSS"]
    max_above = max((float(row.get("hv_ratio") or 0.0) for row in no_tss_above), default=0.0)
    if len(no_tss_above) != 5 or abs(max_above - 1.019938267) > 1e-9:
        errors.append("above-reference no-TSS evidence changed unexpectedly")

    payload = {
        "protocol": "liveopt_reference_robustness_table_p010_p015_20260715_v1",
        "status": "passed" if not errors else "failed",
        "errors": errors,
        "reference_sha256": robustness.get("reference_sha256"),
        "reference_stage_count": robustness.get("reference_stage_count"),
        "rows": rows,
        "above_reference": {
            "method": "LiveOpt w/o TSS",
            "cells_at_1x": len(no_tss_above),
            "max_ratio_at_1x": max_above,
            "cells_at_1_1x": next((row["above_110"] for row in rows if row["method"] == "LiveOpt w/o TSS"), None),
            "cells_at_1_25x": next((row["above_125"] for row in rows if row["method"] == "LiveOpt w/o TSS"), None),
        },
        "archive_cap": {
            "limit": archive.get("archive_cap"),
            "audited_cells": sum(int(row.get("stage_seed_observations") or 0) for row in archive_rows),
            "active_cells": cap_active_cells,
        },
        "provenance": {
            "thinning": str(args.thinning),
            "thinning_sha256": sha256_file(args.thinning),
            "robustness": str(args.robustness),
            "robustness_sha256": sha256_file(args.robustness),
            "archive": str(args.archive),
            "archive_sha256": sha256_file(args.archive),
        },
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.paper_table.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8"
    )
    args.paper_table.write_text(render_tex(rows), encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True))
    if args.strict and errors:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
